In [37]:
import xgboost
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import explained_variance_score
import pandas as pd
import csv

In [38]:
train = pd.read_csv('../../trad-dev/trading-1/data/000660_SK하이닉스.csv', index_col='Unnamed: 0')
train # q23asdasdasd

,시간,시가,고가,저가,종가,전일대비,거래량,거래대금,누적체결매도수량,상장주식수,...,외국인현보유비율,수정주가일자,수정주가비율,기관순매수량,기관누적순매수량,등락주선,등락비율,예탁금,주식회전율,거래성립률
20221101,1530,83900,83900,83900,83900,0,209606,17585940000,1613467,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0
20221101,1520,83900,83900,83700,83800,0,19759,1656510000,1613467,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0
20221101,1519,83900,83900,83800,83900,0,13595,1140060000,1602228,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0
20221101,1518,83800,83900,83700,83900,0,11513,965320000,1596588,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0
20221101,1517,83700,83800,83700,83800,0,21585,1808650000,1595340,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20201023,1449,84400,84500,84400,84500,0,1823,153950000,1117768,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0
20201023,1448,84500,84500,84400,84500,0,2240,189190000,1116900,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0
20201023,1447,84500,84500,84400,84400,0,1302,109940000,1115948,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0
20201023,1446,84500,84500,84400,84500,0,1538,129890000,1115184,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0
20201023,1445,84400,84500,84400,84500,0,2685,226650000,1114460,0,...,0.0,0,0.0,0,0,0,0.0,0,0.0,0.0

In [39]:
train_X = train.iloc[:,0:9]
train_X

,시간,시가,고가,저가,종가,전일대비,거래량,거래대금,누적체결매도수량
20221101,1530,83900,83900,83900,83900,0,209606,17585940000,1613467
20221101,1520,83900,83900,83700,83800,0,19759,1656510000,1613467
20221101,1519,83900,83900,83800,83900,0,13595,1140060000,1602228
20221101,1518,83800,83900,83700,83900,0,11513,965320000,1596588
20221101,1517,83700,83800,83700,83800,0,21585,1808650000,1595340
...,...,...,...,...,...,...,...,...,...
20201023,1449,84400,84500,84400,84500,0,1823,153950000,1117768
20201023,1448,84500,84500,84400,84500,0,2240,189190000,1116900
20201023,1447,84500,84500,84400,84400,0,1302,109940000,1115948
20201023,1446,84500,84500,84400,84500,0,1538,129890000,1115184
20201023,1445,84400,84500,84400,84500,0,2685,226650000,1114460

In [42]:
train_y = train_X.iloc[:,-1]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(
    train_X
    ,train_y
    ,test_size= 0.3
    ,random_state=42
)

In [46]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
k_fold = KFold(n_splits=10, shuffle=True, random_state=42)

In [47]:
# RandomForest
clf = RandomForestClassifier(n_estimators=13,random_state=0, max_depth=8)
scoring = 'accuracy'
score = cross_val_score(clf, train_X, train_y, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)

#80.36 .78229

------------------------------------------------------